steps:
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '-t'
  - 'gcr.io/buho-421304/git-deploy/back:$SHORT_SHA'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/buho-421304/git-deploy/back:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - '$PROJECT_ID-back'
    - '--region=europe-west1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--image=gcr.io/buho-421304/git-deploy/back:$SHORT_SHA'
  env:
  - 'EMBEDDING_MODEL_NAME=${_EMBEDDING_MODEL_NAME}'
  - 'HUGGINGFACEHUB_API_TOKEN=${_HUGGINGFACEHUB_API_TOKEN}'
  - 'OPENAI_API_KEY=${_OPENAI_API_KEY}'