steps:
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/git-deploy/back:$SHORT_SHA'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/git-deploy/back:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - '$PROJECT_ID-back'
    - '--region=europe-west1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--image=gcr.io/$PROJECT_ID/git-deploy/back:$SHORT_SHA'
    - '--update-secrets'
    - 'OPENAI_API_KEY=projects/$PROJECT_NUMBER/secrets/openai_api_key:latest'
    - '--memory=1Gi'